### ISSUE TITLE
Lots of warnings

### ISSUE THREAD

**Issue by paf31** [rintcius/purescript-mathbox#7]
I noticed these in the package set build: https://travis-ci.org/purescript/package-sets/builds/201589015

Most of these should be fixable automatically using pscid actually.

**Comment by rintcius** [comment]
Yes, indeed. That's because this code is generated. Coincidentally I fixed it yesterday in https://github.com/rintcius/purescript-mathbox/pull/6 using `ps-suggest` (all of them were automatically resolved). 

I can publish a new version if you like.

**Comment by paf31** [comment]
If you don't mind, that'd be great.

**Comment by rintcius** [comment]
Ok, published: https://pursuit.purescript.org/packages/purescript-mathbox/0.2.0

**Comment by paf31** [comment]
I've updated the package set, thanks!
